        "deliveryType"                     : "rewardManager",
        "requestClass"                     : "com.evolving.nglm.evolution.RewardManagerRequest",
        "requestTopic"                     : "${topic.fulfillment.rewardmanager.request}",
        "responseTopic"                    : "${topic.fulfillment.rewardmanager.response}",
        "internalTopic"                    : "${topic.fulfillment.rewardmanager.internal}",
        "routingTopic"                     : "${topic.fulfillment.rewardmanager.routing}",
        "deliveryRatePerMinute"            : 60,
        "deliveryGuarantee"                : "atLeastOnce",
        "providerID"                       : "5",
        "providerName"                     : "RewardManager",
        "profileExternalSubscriberIDField" : "subscriber.msisdn"
      },
      {
        "deliveryType"              : "emptyFulfillment_Evolution",
        "requestClass"              : "com.evolving.nglm.evolution.EmptyFulfillmentManager$EmptyFulfillmentRequest",
        "requestTopic"              : "${topic.emptyfulfillment.1.request}",
        "responseTopic"             : "${topic.emptyfulfillment.1.response}",
        "internalTopic"             : "${topic.emptyfulfillment.1.internal}",
        "routingTopic"              : "${topic.emptyfulfillment.1.routing}",
        "deliveryRatePerMinute"     : 60,
        "deliveryGuarantee"         : "atLeastOnce",
        "providerID"                : "1",
        "providerName"              : "Evolution"
      },
      {
        "deliveryType"              : "emptyFulfillment_PostpaidBilling",
        "requestClass"              : "com.evolving.nglm.evolution.EmptyFulfillmentManager$EmptyFulfillmentRequest",
        "requestTopic"              : "${topic.emptyfulfillment.3.request}",
        "responseTopic"             : "${topic.emptyfulfillment.3.response}",
        "internalTopic"             : "${topic.emptyfulfillment.3.internal}",
        "routingTopic"              : "${topic.emptyfulfillment.3.routing}",
        "deliveryRatePerMinute"     : 60,
        "deliveryGuarantee"         : "atLeastOnce",
        "providerID"                : "3",
        "providerName"              : "PostpaidBilling"
      },
      {
        "deliveryType"              : "emptyFulfillment_Store",
        "requestClass"              : "com.evolving.nglm.evolution.EmptyFulfillmentManager$EmptyFulfillmentRequest",
        "requestTopic"              : "${topic.emptyfulfillment.4.request}",
        "responseTopic"             : "${topic.emptyfulfillment.4.response}",
        "internalTopic"             : "${topic.emptyfulfillment.4.internal}",
        "routingTopic"              : "${topic.emptyfulfillment.4.routing}",
        "deliveryRatePerMinute"     : 60,
        "deliveryGuarantee"         : "atLeastOnce",
        "providerID"                : "4",
        "providerName"              : "Store"
      },
      {
