{
 "title": "Support - Hardware",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Used / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by(instance) (irate(node_cpu{mode=\"idle\",instance=~\"$server\"}[5m]) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load - 5 min / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Used / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemAvailable{instance=~\"$server\"}) / node_memory_MemTotal{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by(instance) (1 - node_filesystem_free{device!=\"rootfs\",instance=~\"$server\"} / node_filesystem_size{device!=\"rootfs\",instance=~\"$server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ALERT - Redis Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(redis_memory_used_bytes/redis_config_maxmemory)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Data transfer / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes{device!~\"lo\", device!~\"docker\", instance=~\"$server\"}[5m]) + rate(node_network_transmit_bytes{device!~\"lo\", device!~\"docker\",instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Reads / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_read{instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_written{instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO wait time / node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_ms{instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}