{
 "title": "Support - Throughput",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(com_evolving_nglm_evolution_notificationdelivery_count_total,channel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Evolution Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Evolution Engine TPS By Instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_evolutionengine_event_count_total[$__interval]))",
     "legendFormat": "Total EvE Events"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_evolutionengine_event_count_total[$__interval])) by (process)",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Evolution Engine Events By Event",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_evolutionengine_event_count_total[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Notification Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$channel / Second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "repeat": "channel",
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_notificationdelivery_count_total[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_notificationdelivery_count_total{channel=\"$channel\"}[$__interval])) by (channel, process,status)",
       "legendFormat": "{{channel}}-{{process}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Commodity Delivery Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bonus Percentage OK",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(com_evolving_nglm_evolution_commoditydelivery_count_total{status=\"delivered\"}[${__range_s}s])) * 100 / sum(increase(com_evolving_nglm_evolution_commoditydelivery_count_total[${__range_s}s]))"
      }
     ]
    },
    {
     "title": "Bonus / Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_commoditydelivery_count_total[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_commoditydelivery_count_total[$__interval])) by(process,status)",
       "legendFormat": "{{process}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Purchase Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Purchase Percentage OK",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(com_evolving_nglm_evolution_purchasefulfillment_count_total{status=\"delivered\"}[${__range_s}s])) * 100 / sum(increase(com_evolving_nglm_evolution_purchasefulfillment_count_total[${__range_s}s]))"
      }
     ]
    },
    {
     "title": "Purchase / Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_purchasefulfillment_count_total[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_purchasefulfillment_count_total[$__interval])) by (process,status)",
       "legendFormat": "{{process}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IN Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "IN / Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval])) by (process,status)",
       "legendFormat": "{{process}}-{{status}}"
      }
     ]
    },
    {
     "title": "Average Call Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_seconds_total[$__interval]))/sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval]))",
       "legendFormat": "All"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_seconds_total[$__interval]))by(process,status)/sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval]))by(process,status)",
       "legendFormat": "{{process}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "3rdParty Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Call / Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Call" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval])) by (process,status)",
       "legendFormat": "{{process}}-{{status}}"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval])) by (name,status)",
       "legendFormat": "{{name}}-{{status}}"
      }
     ]
    },
    {
     "title": "Average Call Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval]))/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))",
       "legendFormat": "All"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval])) by(process,status)/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))by(process,status)",
       "legendFormat": "{{process}}-{{status}}"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval])) by(name,status)/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))by(name,status)",
       "legendFormat": "{{name}}-{{status}}"
      }
     ]
    }
   ]
  }
 ]
}