{
 "title": "Platform Health Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   },
   {
    "name": "connector",
    "label": "CDR Source",
    "query": {
     "query": "com_evolving_nglm_core_filesourcetask_filesprocessedcount"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Health Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage / Node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent", "label": "% CPU" }
     ],
     "targets": [
      {
       "expr": "100 - avg by(instance) (irate(node_cpu{mode=\"idle\",instance=~\"$server\"}[5m]) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage / Node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent", "label": "% Memory" }
     ],
     "targets": [
      {
       "expr": "100 * (node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemAvailable{instance=~\"$server\"}) / node_memory_MemTotal{instance=~\"$server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Space Usage / Node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(1 - node_filesystem_free{device!~\".*docker.*\",device=~\"/dev.*\",instance=~\"$server\"} / node_filesystem_size{device!~\".*docker.*\",device=~\"/dev.*\",instance=~\"$server\"})",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "System Load - 5 Minute / Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit", "label": "Load%" }
     ],
     "targets": [
      {
       "expr": "node_load5{} / scalar(sum(machine_cpu_cores)) ",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CDR Processing Backlog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDR Current File Lag / Backlog",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_lag{topic=~\"($connector)-fileconnector\"}) by (topic)",
       "legendFormat": "{{ topic }}"
      }
     ]
    }
   ]
  },
  {
   "title": "External API Processing Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Call / Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Call" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval])) by (process,status)",
       "legendFormat": "{{process}}-{{status}}"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval])) by (name,status)",
       "legendFormat": "{{name}}-{{status}}"
      }
     ]
    },
    {
     "title": "Average Call Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval]))/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))",
       "legendFormat": "All"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval])) by(process,status)/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))by(process,status)",
       "legendFormat": "{{process}}-{{status}}"
      },
      {
       "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval])) by(name,status)/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))by(name,status)",
       "legendFormat": "{{name}}-{{status}}"
      }
     ]
    }
   ]
  },
  { "title": "Maintenance Action Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Maintenance Action History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status",
       "id": "6",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "actionStartDate", "id": "4", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "actionStartDate"
    }
   ]
  },
  {
   "title": "Request Status Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "requestDate"
    }
   ]
  },
  {
   "title": "Maintenance Request Stat",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "requestDate", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "requestDate"
    }
   ]
  }
 ]
}