{
 "title": "Support - Hardware",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "% CPU" }
   ],
   "targets": [
    {
     "expr": "100 - avg by(instance) (irate(node_cpu{mode=\"idle\",instance=~\"$server\"}[5m]) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "% Memory" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal{instance=~\"$server\"} - node_memory_MemAvailable{instance=~\"$server\"}) / node_memory_MemTotal{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Reads / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_read{instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_written{instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load - 5 Minute / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Space Usage / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - node_filesystem_free{device!=\"rootfs\",device=~\"/dev.*\",instance=~\"$server\"} / node_filesystem_size{device!=\"rootfs\",device=~\"/dev.*\",instance=~\"$server\"})",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Data Transfer / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes{device!~\"lo\", device!~\"docker\", instance=~\"$server\"}[5m]) + rate(node_network_transmit_bytes{device!~\"lo\", device!~\"docker\",instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO Wait Time / Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_ms{instance=~\"$server\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}