{
 "title": "Next Best Offer",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Presentation Live Chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "No. of Presentations",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.action: Allocate AND filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Acceptance Live Chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      {
       "$$hashKey": "object:142",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "filter.action: Redeem AND filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OFFERS ACCEPTED",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "{{filter.acceptedOffer}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:352",
       "fake": true,
       "field": "filter.acceptedOffer",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1y", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:329",
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {
        "script": " long noAcc = 0; if (doc['filter.action'].value == 'Redeem' && doc['filter.returnCode'].value == 'SUCCESS') { noAcc = doc['count'].value;} return noAcc;"
       },
       "type": "sum"
      }
     ],
     "query": "filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Redemption Rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "settings": {
        "script": " long noAcc = 0; if (doc['filter.action'].value == 'Redeem' && doc['filter.returnCode'].value == 'SUCCESS') { noAcc = doc['count'].value;} return noAcc;"
       },
       "type": "sum"
      },
      {
       "field": "period",
       "hide": true,
       "id": "3",
       "settings": {
        "script": " long noPres = 0; if (doc['filter.action'].value == 'Allocate' && doc['filter.returnCode'].value == 'SUCCESS') { noPres = doc['count'].value;} return noPres;"
       },
       "type": "sum"
      },
      {
       "id": "4",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "if (params.var2>0){params.var1/params.var2*100} else 0;"
       },
       "type": "bucket_script"
      }
     ],
     "query": "filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Accepted Offers",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "filter.acceptedOffer",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "filter.action: Redeem AND filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Revenue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Revenue per Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.salesChannel",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metric.totalAmount", "id": "1", "type": "sum" }
     ],
     "query": "filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Revenue per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metric.totalAmount", "id": "1", "type": "sum" }
     ],
     "query": "filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "REVENUE PER OFFER",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "{{filter.offer}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:2924",
       "fake": true,
       "field": "filter.offer",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2874",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2872",
       "field": "metric.totalAmount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "filter.returnCode: SUCCESS",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}