{
 "title": "Admin - Monitoring Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "channel_name", "label": "Channel Name", "query": { "query": "messagegateway" } },
   {
    "name": "dimension",
    "label": "Dimension",
    "query": "{\"find\" : \"fields\", \"type\": \"keyword\"}"
   },
   { "name": "period", "label": "period", "query": "86400000" }
  ]
 },
 "panels": [
  { "title": "Notifications - $channel_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_notificationdelivery_count_total{tenant=\"replaceWithTenantID\"}[${__range_s}s])) by(channel, status)",
     "legendFormat": " {{channel}} {{status}}  "
    }
   ]
  },
  {
   "title": "Success and Failure (Message / Day)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "locale", "label": "Message" }
   ],
   "targets": [
    {
     "expr": "sum by(channel, status)(increase(com_evolving_nglm_evolution_notificationdelivery_count_total{tenant=\"replaceWithTenantID\"}[1d]))",
     "legendFormat": "{{channel}} / {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure Rate (Message / Second)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Message " }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_notificationdelivery_count_total{tenant=\"replaceWithTenantID\"}[$__interval])) by (channel, status)",
     "legendFormat": "{{channel}} / {{status}}"
    }
   ]
  },
  { "title": "BDR -  Bonus Detail Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "period:$period",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Success and Failure (Record / Day)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 3, "y": 17 },
   "yaxes": [
    { "format": "locale", "label": "Record" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.returnCode",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "period:$period",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Success and Failure Rate (Record / Second)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Record" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.returnCode",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      {
       "field": "period",
       "hide": true,
       "id": "4",
       "type": "min"
      },
      {
       "id": "5",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": { "script": "(params.var1/params.var2)*1000" },
       "type": "bucket_script"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "VDR - Voucher Detail Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_voucher_change_count_total{tenant=\"replaceWithTenantID\"}[${__range_s}s])) by(module ,operation, status)",
     "legendFormat": "{{module }} / {{operation}} / {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure (Record / Day)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 3, "y": 32 },
   "yaxes": [
    { "format": "locale", "label": "Record" }
   ],
   "targets": [
    {
     "expr": "sum by(module ,operation, status)(increase(com_evolving_nglm_evolution_voucher_change_count_total{tenant=\"replaceWithTenantID\"}[1d]))",
     "legendFormat": "{{module }} / {{operation}} / {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure Rate (Record / Second)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Record" }
   ],
   "targets": [
    {
     "expr": "sum by(module ,operation, status)(rate(com_evolving_nglm_evolution_voucher_change_count_total{tenant=\"replaceWithTenantID\"}[$__interval]))",
     "legendFormat": "{{module }} / {{operation}} / {{status}}"
    }
   ]
  },
  { "title": "ODR - Offer Detail Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_purchasefulfillment_count_total{tenant=\"replaceWithTenantID\"}[${__range_s}s]))by(module, status)",
     "legendFormat": "{{module}} / {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure (Record / Day)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Record" }
   ],
   "targets": [
    {
     "expr": "sum by(module,status)(increase(com_evolving_nglm_evolution_purchasefulfillment_count_total{tenant=\"replaceWithTenantID\"}[1d]))",
     "legendFormat": "{{module}} {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure Rate (Record / Second)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Record" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_purchasefulfillment_count_total{tenant=\"replaceWithTenantID\"}[$__interval])) by (module, status)",
     "legendFormat": "{{module}} / {{status}}"
    }
   ]
  },
  { "title": "Fulfillment Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 17, "w": 3, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(increase (com_evolving_nglm_evolution_infulfillmentdelivery_count_total{tenant=\"replaceWithTenantID\"}[${__range_s}s])) by(process, status)",
     "legendFormat": "{{process}} / {{status}}"
    }
   ]
  },
  {
   "title": "Fulfillment (Count / Day)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 10, "x": 3, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Fulfillment" }
   ],
   "targets": [
    {
     "expr": "sum(increase (com_evolving_nglm_evolution_infulfillmentdelivery_count_total{tenant=\"replaceWithTenantID\"}[1d])) by(process, operation, status)",
     "legendFormat": "{{process}} / {{operation}} / {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure Rate (Fulfillment / Second)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Fulfillment" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total{tenant=\"replaceWithTenantID\"}[$__interval])) by (process,operation, status)",
     "legendFormat": "{{process}} / {{operation}} / {{status}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_seconds_total{tenant=\"replaceWithTenantID\"}[$__interval]))/sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total{tenant=\"replaceWithTenantID\"}[$__interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_seconds_total{tenant=\"1\"}[$__interval]))by(process,operation,status)/sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total{tenant=\"replaceWithTenantID\"}[$__interval]))by(process,operation,status)",
     "legendFormat": "{{process}} / {{operation}} / {{status}}"
    }
   ]
  },
  { "title": "3'rd Party API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_thirdpartyaccess_count_total{tenant=\"replaceWithTenantID\"}[${__range_s}s]))by(name, status)",
     "legendFormat": "{{name}} / {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure (Count / Day)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 86 },
   "yaxes": [
    { "format": "short", "label": "Call" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_thirdpartyaccess_count_total{tenant=\"replaceWithTenantID\"}[1d]))by(name, status)",
     "legendFormat": "{{name}} / {{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure Rate (Call / Second)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 86 },
   "yaxes": [
    { "format": "short", "label": "Call" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total{tenant=\"replaceWithTenantID\"}[$__interval])) by(name, status)",
     "legendFormat": "{{name}} / {{status}}"
    }
   ]
  },
  { "title": "Subscriber Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Subscribers",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Subscriber Count by $dimension",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 99 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.stratum.$dimension",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "GUI - User Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase (com_evolution_fwkauth_users_connected{tenantID=\"replaceWithTenantID\"}[${__range_s}s])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Success and Failure (Count / Day)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "yaxes": [
    { "format": "Misc", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(increase(com_evolution_fwkauth_user_authentication_requests{tenantID=\"replaceWithTenantID\"}[1d]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Connection Count per Browser Type",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 109 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "browser",
       "id": "11",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Count per Action Type",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 109 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "shortDescription",
       "id": "11",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Audit Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}