{
 "title": "Business _ Offer and Voucher Dashboard",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module",
    "label": "Module Name",
    "query": "{\"find\": \"terms\", \"field\": \"filter.module\"}"
   },
   {
    "name": "featureODR",
    "label": "ODR Feature",
    "query": "{\"find\": \"terms\", \"field\": \"filter.feature\"}"
   },
   {
    "name": "featureVDR",
    "label": "VDR Feature",
    "query": "{\"find\": \"terms\", \"field\": \"filter.feature\"}"
   },
   {
    "name": "salesChannel",
    "label": "Sales Channel",
    "query": "{\"find\": \"terms\", \"field\": \"filter.salesChannel\"}"
   },
   {
    "name": "offerObjectives",
    "label": "Offer Objectives",
    "query": "{\"find\": \"terms\", \"field\": \"filter.offerObjectives\"}"
   },
   {
    "name": "voucherName",
    "label": "Voucher Name",
    "query": "{\"find\": \"terms\", \"field\": \"filter.voucher\"}"
   },
   {
    "name": "action",
    "label": "Action",
    "query": "{\"find\": \"terms\", \"field\": \"filter.action\"}"
   },
   { "name": "interval", "label": "interval", "query": "1d" }
  ]
 },
 "panels": [
  { "title": "Offer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ODR per Channel over $interval",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.salesChannel",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.salesChannel:$salesChannel",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ODR Daily Count per Channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.salesChannel",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.salesChannel:$salesChannel",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ODR per Feature over $interval",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.feature",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.feature:$featureODR AND filter.module:$module",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ODR Daily Count per Feature ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.feature",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.feature:$featureODR AND filter.module:$module",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ODR per offerObjectives over $interval",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.offerObjectives",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.offerObjectives:$offerObjectives",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ODR Daily Count per offerObjectives",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.offerObjectives",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.offerObjectives:$offerObjectives",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Purchased Offers over $interval",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.offer",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": false,
       "id": "4",
       "settings": {
        "script": "long total = 0; if (doc['filter.returnCode'].value == 'SUCCESS') { total = doc['count'].value;} return total;"
       },
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ODR Amount Spent per Day per Payment Mean",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.meanOfPayment",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric.totalAmount",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Voucher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "VDR per Feature over $interval",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.feature",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.feature:$featureVDR AND filter.module:$module",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VDR Daily Count per Feature ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.feature",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.feature:$featureVDR AND filter.module:$module",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VDR Daily Count per Action",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.action",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.action:$action",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Ratio of Redeemed Vouchers per Delivered Vouchers per Suppliers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent", "label": "Ratio" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.supplier",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "settings": {
        "script": "long total = 0; if (doc['filter.action'].value == 'Redeem') { total = doc['count'].value;} return total;"
       },
       "type": "sum"
      },
      {
       "field": "count",
       "hide": true,
       "id": "4",
       "settings": {
        "script": "long total = 0; if (doc['filter.action'].value == 'Deliver' ) { total = doc['count'].value;} return total;"
       },
       "type": "sum"
      },
      {
       "id": "5",
       "pipelineVariables": [
        { "name": "redeem", "pipelineAgg": "1" },
        { "name": "deliver", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.redeem/params.deliver" },
       "type": "bucket_script"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VDR per Voucher over $interval",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.voucher",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "query": "filter.voucher:$voucherName",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VDR per Supplier over $interval",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.supplier",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "count", "id": "1", "type": "sum" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}