{
 "title": "DevOps - Cluster Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Controller and Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controller",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Partitions",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UnderReplicated Partitions",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}