{
 "title": "Tiered Program",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "loyProgram",
    "label": "Tiered Program",
    "query": "{\"find\" : \"terms\",\"field\": \"filter.loyaltyProgram\", \"size\": 10000}"
   },
   {
    "name": "tier",
    "label": "Tier",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.tier\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   {
    "name": "tierChangeType",
    "label": "Tier Change Type",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.tierChangeType\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   {
    "name": "previousTier",
    "label": "Previous Tier",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.previousTier\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   {
    "name": "newTier",
    "label": "New Tier",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.newTier\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   { "name": "downVar", "label": "downVar", "query": "downgrade" },
   { "name": "upgradeVar", "label": "upgradeVar", "query": "upgrade" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "subscrStatus",
    "label": "Customer Status",
    "query": "{\"find\" : \"terms\",\"field\": \"filter.evolutionSubscriberStatus\", \"size\": 10000}"
   }
  ]
 },
 "panels": [
  {
   "title": "Tiered Program Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Customer Count for \"$loyProgram\"",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.tier",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": 1, "offset": "-06h", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Count Evolution for \"$loyProgram\" for last $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "filter.tier",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Daily Count for \"$loyProgram\" and Tier: $tier",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "locale", "label": "Number of subscribers" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.tier",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.tier:$tier",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Daily Count per Tier for \"$loyProgram\"",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "filter.tier",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Tiered Program Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tiered Program Transition",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "format": "locale",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.tierChangeType",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.tierChangeType:$tierChangeType AND filter.previousTier:$previousTier AND filter.newTier:$newTier",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Count for \"$loyProgram\" and $tierChangeType from $previousTier to $newTier",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.tierChangeType",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.tierChangeType:$tierChangeType AND filter.previousTier:$previousTier AND filter.newTier:$newTier",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Tier Changes for \"$loyProgram\" by Tier Transition",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "filter.previousTier",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "filter.newTier",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "filter.tierChangeType",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.tierChangeType:$tierChangeType AND filter.previousTier:$previousTier AND filter.newTier:$newTier",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Upgrade and Downgrade Daily Count for \"$loyProgram\" from $previousTier to $newTier",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "locale", "label": "Count" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.tierChangeType",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND (filter.tierChangeType:$downVar OR filter.tierChangeType:$upgradeVar) AND filter.previousTier:$previousTier AND filter.newTier:$newTier",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Opt-in and Opt-out Daily Count for \"$loyProgram\" from $previousTier to $newTier",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 17 },
     "yaxes": [
      { "format": "locale", "label": "Number of subscribers" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.tierChangeType",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND (NOT(filter.tierChangeType:$downVar OR filter.tierChangeType:$upgradeVar)) AND filter.tierChangeType:$tierChangeType AND filter.previousTier:$previousTier AND filter.newTier:$newTier",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Tiered Program Points Redemption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Points Daily Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "locale", "label": "Number of points" }
   ],
   "targets": [
    {
     "alias": "Redeemed",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 1, "offset": "-06h", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "metric.rewards.redeemed",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "filter.loyaltyProgram:$loyProgram AND filter.tier:$newTier",
     "timeField": "timestamp"
    },
    {
     "alias": "Earned",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 1, "offset": "-06h", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "metric.rewards.earned",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "filter.loyaltyProgram:$loyProgram AND filter.tier:$newTier",
     "timeField": "timestamp"
    },
    {
     "alias": "Expired",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric.rewards.expired",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "filter.loyaltyProgram:$loyProgram AND filter.tier:$newTier",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Points Summary by Tier for \"$loyProgram\"",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      },
      {
       "fake": true,
       "field": "filter.tier",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "filter.redeemer",
       "id": "11",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "metric.rewards.earned",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "metric.rewards.expired",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "metric.rewards.redeemed",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "filter.loyaltyProgram:$loyProgram AND filter.tier:$newTier",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Point Daily Count by Sales Channel",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1755",
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      },
      {
       "$$hashKey": "object:1756",
       "field": "filter.salesChannel",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1753",
       "field": "metric.totalAmount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Redemption Trends -  Sales Channel Graphic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.salesChannel",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "metric.totalAmount", "id": "1", "type": "sum" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Tiered Program Customer Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Customer Daily Count per Tier for \"$subscrStatus\" status for Program \"$loyProgram\"",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "locale", "label": "Number of Customers" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.evolutionSubscriberStatus",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "15" },
         "type": "terms"
        },
        {
         "field": "filter.tier",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.evolutionSubscriberStatus:$subscrStatus AND filter.tier:$tier",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Daily Count per Tier for \"$subscrStatus\" status for \"$loyProgram\"",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        },
        {
         "fake": true,
         "field": "filter.evolutionSubscriberStatus",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "15" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "filter.tier",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.evolutionSubscriberStatus:$subscrStatus AND filter.tier:$tier",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}