{
 "title": "DevOps - Redis",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "addr",
    "query": {
     "query": "label_values(redis_connected_clients, addr)"
    }
   },
   {
    "name": "command",
    "query": {
     "query": "label_values(redis_command_call_duration_seconds_count, cmd)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs", "label": "Microsecond" }
   ],
   "targets": [
    {
     "expr": "(rate(redis_command_call_duration_seconds_sum{addr = \"$addr\", cmd =~ \".*$command.*\"}[1m]) / rate(redis_command_call_duration_seconds_count{addr =\"$addr\", cmd =~ \"$command\"}[1m])) * 1000000",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Snapshot (RDB) Disk Store Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs", "label": "RDB" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_last_bgsave_duration_sec{} * 1000000"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) - sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$addr\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "call" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_command_call_duration_seconds_count{addr=~\"$addr\"} [1m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{addr=~\"$addr\"}  / redis_config_maxmemory{addr=~\"$addr\"} )"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=\"$addr\"}[5m])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=\"$addr\"}[5m])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Hits / Misses per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Irate" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=\"$addr\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=\"$addr\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$addr\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_config_maxmemory{addr=~\"$addr\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{addr=~\"$addr\"}[5m])",
     "legendFormat": "{{addr}}"
    }
   ]
  }
 ]
}