{
 "title": "Challenges Program Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "loyProgram",
    "label": "Level Program",
    "query": "{\"find\" : \"terms\",\"field\": \"filter.loyaltyProgram\", \"size\": 10000}"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.level\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   {
    "name": "levelChangeType",
    "label": "Level Change Type",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.levelChangeType\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   {
    "name": "previousLevel",
    "label": "Previous Level",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.previousLevel\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   {
    "name": "newLevel",
    "label": "New Level",
    "query": "{\"find\" : \"terms\", \"field\": \"filter.newLevel\",\"query\": \"filter.loyaltyProgram:$loyProgram\"}"
   },
   { "name": "downVar", "label": "downVar", "query": "downgrade" },
   { "name": "upgradeVar", "label": "upgradeVar", "query": "upgrade" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "segment",
    "label": "Segments",
    "query": "{\"find\" : \"terms\",\"field\": \"filter.stratum.XXX\", \"size\": 10000}"
   }
  ]
 },
 "panels": [
  {
   "title": "Challenges Program Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Customer Count for Level Program: \"$loyProgram\"",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.level",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": 1, "offset": "-06h", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Count Evolution for Level Program: \"$loyProgram\" over $interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "filter.level",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Daily Count for Level Program: \"$loyProgram\" and Level: $level",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "locale", "label": "Number of subscribers" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.level:$level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Daily Count per Level for Level Program: \"$loyProgram\"",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "filter.level",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Challenges Program Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Level Program Transition",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "format": "locale",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.levelChangeType",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.levelChangeType:$levelChangeType AND filter.previousLevel:$previousLevel AND filter.newLevel:$newLevel",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Count for Level Program: \"$loyProgram\" and Level Change Type: \"$levelChangeType\" from $previousLevel to $newLevel",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.levelChangeType",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.levelChangeType:$levelChangeType AND filter.previousLevel:$previousLevel AND filter.newLevel:$newLevel",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Level Changes for Level Program: \"$loyProgram\" by Level Transition",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "filter.previousLevel",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "filter.newLevel",
         "id": "7",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "filter.levelChangeType",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.levelChangeType:$levelChangeType AND filter.previousLevel:$previousLevel AND filter.newLevel:$newLevel",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Upgrade and Downgrade Daily Count for Level Program: \"$loyProgram\" from $previousLevel to $newLevel",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "locale", "label": "Count" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.levelChangeType",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND (filter.levelChangeType:$downVar OR filter.levelChangeType:$upgradeVar) AND filter.previousLevel:$previousLevel AND filter.newLevel:$newLevel",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Opt-in and Opt-out Daily Count for Level Program: \"$loyProgram\" from $previousLevel to $newLevel",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 17 },
     "yaxes": [
      { "format": "locale", "label": "Number of subscribers" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "fitler.levelChangeType",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND (NOT(filter.levelChangeType:$downVar OR filter.levelChangeType:$upgradeVar)) AND filter.levelChangeType:$levelChangeType AND filter.previousLevel:$previousLevel AND filter.newLevel:$newLevel",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Challenges Program Score Redemption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Score Daily Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "locale", "label": "Score" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": 1, "offset": "-06h", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "metric.score",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.level:$newLevel",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Score Summary by Level for Level Program: \"$loyProgram\"",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        },
        {
         "fake": true,
         "field": "filter.level",
         "id": "9",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        },
        {
         "field": "metric.score",
         "id": "6",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.loyaltyProgram:$loyProgram AND filter.level:$newLevel",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Challenges Program Customer Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Customer Daily Count per Level for \"$segment\" for Level Program: \"$loyProgram\"",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "locale", "label": "Number of Customers" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "filter.stratum.XXX",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "fitler.level",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "timestamp",
         "id": "4",
         "settings": { "interval": "1d", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.stratum.XXX:$segement AND filter.level:$level",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Customer Daily Count per Level for \"$segment\" for Level Program: \"$loyProgram\"",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "timestamp",
         "id": "5",
         "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        },
        {
         "fake": true,
         "field": "filter.stratum.XXX",
         "id": "6",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "fitler.level",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "filter.stratum.XXX:$segment AND filter.level:$level",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}