{
 "title": "DevOps - Kafka Lags",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,5s,10s,20s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "topics",
    "label": "Topics",
    "query": "dmpcarprofile,recordsubscriberid,acceptancelog,interactionlog,presentationlog,presentationdetailslog"
   },
   {
    "name": "consumer_group",
    "label": "consumer group",
    "query": {
     "query": "query_result(kafka_consumergroup_group_lag{})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topic Lags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Estimated Lag in Seconds" }
   ],
   "targets": [
    {
     "expr": "avg(rate(kafka_consumergroup_group_lag_seconds{topic=~\"[[topics]]\"}[$interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Lags in Consumer Groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Estimated Lag in Seconds" }
   ],
   "targets": [
    {
     "expr": "avg(rate(kafka_consumergroup_group_lag_seconds{topic=~\"[[topics]]\"}[$interval])) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Max Topic Lags",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Estimated Lag in Seconds" }
   ],
   "targets": [
    {
     "expr": "max(rate(kafka_consumergroup_group_lag_seconds{topic=~\"[[topics]]\"}[$interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag per Consumer id",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s", "label": "Estimated Lag in Seconds" }
   ],
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag_seconds{group=~\"$consumer_group\"})",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Estimated Lag in Seconds per Topics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s", "label": "Estimated Lag in Seconds" }
   ],
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds{group=~\"$consumer_group\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Estimated Lag in Seconds per Real Time Topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds{group=~\"$consumer_group\", topic=~\"$topics\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}