{
 "title": "MAG - API Monitoring Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Application API - HTTP requests coming from mobile app and web site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Count over $interval",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(increase(mag_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$interval]))by(instance, URI))",
       "legendFormat": "{{instance}}/ -- {{URI}}"
      }
     ]
    },
    {
     "title": "Requests / Day",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Request" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mag_requests_seconds_count{tenant=\"replaceWithTenantID\"}[1d]))by(instance, URI)",
       "legendFormat": "{{instance}}/ --{{URI}}"
      }
     ]
    },
    {
     "title": "Requests / Second",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Request" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mag_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$__rate_interval])) by(instance, URI)",
       "legendFormat": "{{instance}}/ -- {{URI}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Duration (ms)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mag_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$__rate_interval]))by(instance)/sum(rate(mag_requests_seconds_sum{tenant=\"replaceWithTenantID\"}[$__rate_interval]))by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pool Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "(globalRequests_lastPoolUsage{tenant=\"replaceWithTenantID\"})",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Congestion Percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percent", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "(globalRequests_lastConPer{tenant=\"replaceWithTenantID\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Authentication API - requests sent to external systems for AAA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(increase(mag_loyaltyApi_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$interval]))by(instance))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Requests / Day",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 5, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Request" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mag_loyaltyApi_requests_seconds_count{tenant=\"replaceWithTenantID\"}[1d]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Request" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mag_loyaltyApi_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Duration (ms)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mag_loyaltyApi_requests_seconds_sum{tenant=\"replaceWithTenantID\"}[$__rate_interval]))by(instance)/sum(rate(mag_loyaltyApi_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$__rate_interval]))by(instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "(LoyaltyApi_lastPoolUsage{tenant=\"replaceWithTenantID\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Congestion Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "(LoyaltyApi_lastPoolUsage{tenant=\"replaceWithTenantID\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Evolution API - requests sent to Evolution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Overall Count over $interval",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(mag_evo_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$interval]))by(instance, URL))",
     "legendFormat": "{{instance}} / {{URL}}"
    }
   ]
  },
  {
   "title": "Requests / Day",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Request" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mag_evo_requests_seconds_count{tenant=\"replaceWithTenantID\"}[1d]))by(instance, URL)",
     "legendFormat": "{{instance}}  / {{URL}}"
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Request" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mag_evo_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$__rate_interval])) by(instance, URL)",
     "legendFormat": "{{instance}} / {{URL}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Duration (ms)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mag_evo_requests_seconds_sum{tenant=\"replaceWithTenantID\"}[$__rate_interval]))by(instance)/sum(rate(mag_evo_requests_seconds_count{tenant=\"replaceWithTenantID\"}[$__rate_interval]))by(instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent", "label": "percent" }
   ],
   "targets": [
    {
     "expr": "EVO_lastPoolUsage{tenant=\"replaceWithTenantID\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Congestion Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "EVO_lastConPer{tenant=\"replaceWithTenantID\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  }
 ]
}