{
 "title": "Support - CDR",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "connector",
    "label": "CDR Source",
    "query": "com_evolving_nglm_core_filesourcetask_filesprocessedcount"
   },
   {
    "name": "stream_connector",
    "label": "Stream Source",
    "query": {
     "query": "com_evolving_nglm_core_streamsourcetask_totalrecordcount"
    }
   },
   { "name": "interval", "query": "1m" }
  ]
 },
 "panels": [
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "File Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CDR Current File Lag / Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_total_lag{group=~\"fileconnector-($connector)_file_connector.*\"}",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Total Record $interval - status OK",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": "Total Record $interval - status KO",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": " $connector File - Current / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_filesourcetask_filesprocessedcount{connectorName=~\"($connector)_file_connector\"}[5m])) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    },
    { "legendFormat": "{{connectorName}}" }
   ]
  },
  {
   "title": " $connector Record - Current / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_core_filesourcetaskrecord_recordcount{recordType=~\"$connector.*\"}[10m])) by (recordType)",
     "legendFormat": "{{ recordType }}"
    }
   ]
  },
  {
   "title": "ALERT - Number CDR File - Last Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_core_filesourcetask_filesprocessedcount{connectorName=~\"($connector)_file_connector\"}[1h])) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  { "title": "Stream Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": " $connector Record - Current / Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_streamsourcetask_totalrecordcount{connectorName=~\"$stream_connector.*\"}[10m])) by (instance, connectorName)",
     "legendFormat": "{{instance}} {{ connectorName }}"
    }
   ]
  },
  {
   "title": "Total Record over $interval - status OK",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount{connectorName=~\"($stream_connector)_stream_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount{connectorName=~\"($stream_connector)_stream_connector\"}[$interval]) + increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount{connectorName=~\"($stream_connector)_stream_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": "Total Record over $interval - status KO",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount{connectorName=~\"($stream_connector)_stream_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount{connectorName=~\"($stream_connector)_stream_connector\"}[$interval]) + increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount{connectorName=~\"($stream_connector)_stream_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  }
 ]
}