{
 "title": "Support - Throughput",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Evolution Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Evolution Engine TPS By Instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_evolutionengine_event_count_total[$__interval]))",
     "legendFormat": "Total EvE Events"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_evolutionengine_event_count_total[$__interval])) by (process)",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Evolution Engine Events By Event",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_evolutionengine_event_count_total[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Notification Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "notification / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_notificationdelivery_count_total[$__interval])) by (channel)",
     "legendFormat": "Total-{{channel}}"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_notificationdelivery_count_total[$__interval])) by (channel,status)",
     "legendFormat": "{{channel}}-{{status}}"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_notificationdelivery_count_total[$__interval])) by (process,channel,status)",
     "legendFormat": "{{process}}-{{channel}}-{{status}}"
    }
   ]
  },
  { "title": "Commodity Delivery Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Bonus Total OK",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_commoditydelivery_count_total{status=\"delivered\"}[${__range_s}s])) * 100 / sum(increase(com_evolving_nglm_evolution_commoditydelivery_count_total[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "bonus / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_commoditydelivery_count_total[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_commoditydelivery_count_total[$__interval])) by(process,status)",
     "legendFormat": "{{process}}-{{status}}"
    }
   ]
  },
  { "title": "Purchase Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Purchase Total OK",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_purchasefulfillment_count_total{status=\"delivered\"}[${__range_s}s])) * 100 / sum(increase(com_evolving_nglm_evolution_purchasefulfillment_count_total[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "purchase / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_purchasefulfillment_count_total[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_purchasefulfillment_count_total[$__interval])) by (process,status)",
     "legendFormat": "{{process}}-{{status}}"
    }
   ]
  },
  { "title": "IN Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "IN / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval])) by (process,status)",
     "legendFormat": "{{process}}-{{status}}"
    }
   ]
  },
  {
   "title": "average call duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_seconds_total[$__interval]))/sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_seconds_total[$__interval]))by(process,status)/sum(rate(com_evolving_nglm_evolution_infulfillmentdelivery_count_total[$__interval]))by(process,status)",
     "legendFormat": "{{process}}-{{status}}"
    }
   ]
  },
  { "title": "ThirdParty Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "call / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval])) by (process,status)",
     "legendFormat": "{{process}}-{{status}}"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval])) by (name,status)",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  },
  {
   "title": "average call duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval]))/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval])) by(process,status)/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))by(process,status)",
     "legendFormat": "{{process}}-{{status}}"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_seconds_total[$__interval])) by(name,status)/sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_count_total[$__interval]))by(name,status)",
     "legendFormat": "{{name}}-{{status}}"
    }
   ]
  }
 ]
}