{
 "title": "Business - Base Analytics Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dimension1",
    "label": "First Dimension",
    "query": "{\"find\" : \"fields\", \"type\": \"keyword\"}"
   },
   {
    "name": "dimension2",
    "label": "Second Dimension",
    "query": "{\"find\" : \"fields\", \"type\": \"keyword\"}"
   },
   {
    "name": "dimension3",
    "label": "Third Dimension",
    "query": "{\"find\" : \"fields\", \"type\": \"keyword\"}"
   },
   {
    "name": "metrics",
    "label": "Metrics",
    "query": "{\"find\" : \"fields\", \"type\": \"number\"}"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Customers by Dimension",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "Customer" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimension1",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimension2",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimension3",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of Customers by $dimension1",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.stratum.$dimension1",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "3", "settings": { "interval": "1s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Evolution of the Number of Customers by $dimension1 over $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimension1",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of Customers by $dimension2",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.stratum.$dimension2",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "3", "settings": { "interval": "1s", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Evolution of the Number of Customers by $dimension2 over $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimension2",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of Customers by $dimension3",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter.stratum.$dimension3",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Evolution of the Number of Customers by $dimension3 over $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimension3",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "$metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "metrics" },
  {
   "title": "Average of $metrics",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimension1",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "filter.stratum.$dimension2",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "filter.stratum.$dimension3",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "metric.custom.$metrics",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "5",
       "meta": {},
       "pipelineVariables": [
        { "name": "d", "pipelineAgg": "4" },
        { "name": "n", "pipelineAgg": "1" }
       ],
       "settings": { "script": "params.d / params.n" },
       "type": "bucket_script"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}