{
 "title": "DevOps - Kafka Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Controller and Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Controller",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_activecontrollercount",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Partitions",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_partitioncount",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Offline Partitions",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_offlinepartitionscount",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "UnderReplicated Partitions",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_underreplicatedpartitions",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Produced",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Rate " }
   ],
   "targets": [
    {
     "expr": "kmf_services_produce_service_records_produced_rate"
    }
   ]
  },
  {
   "title": "99.9 Delay (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_999th"
    }
   ]
  },
  {
   "title": "Max delay (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_max"
    }
   ]
  },
  {
   "title": "Min delay (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_avg"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_lost_rate"
    }
   ]
  },
  {
   "title": "Total Lag (now)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kafka_burrow_total_lag)" }
   ]
  },
  {
   "title": "Total Kafka Lag (History)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_total_lag{group!~\".*GuiManager.*\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Real time Lag (History)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_total_lag{group=\"acceptancelog\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-request-group\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-async-group\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-routing-group\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-provisioning\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"presentationlog\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-routing-group\"}",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}