{
 "title": "Admin - Overall Monitoring Dashboard - rk",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "connector",
    "label": "File Source",
    "query": {
     "query": "com_evolving_nglm_core_filesourcetask_filesprocessedcount"
    }
   },
   {
    "name": "stream_connector",
    "label": "Stream Source",
    "query": {
     "query": "com_evolving_nglm_core_streamsourcetask_totalrecordcount"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alert List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - avg by(instance) (irate(node_cpu{mode=\"idle\"}[1h]) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal - node_memory_MemAvailable) / node_memory_MemTotal",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Space Usage / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max by(instance) (1 - node_filesystem_free{device!=\"rootfs\"} / node_filesystem_size{device!=\"rootfs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Writes / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_bytes_written{}[1h]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Reads / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_bytes_read{}[1h]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Load / Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (rate(node_network_receive_bytes{device!~\"lo\", device!~\"docker\"}[1h]) + rate(node_network_transmit_bytes{device!~\"lo\", device!~\"docker\"}[1h]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File Data Feed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current File Backlog",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "kafka_burrow_total_lag{group=~\"fileconnector-($connector)_file_connector.*\"}",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "File Rate (Count / Second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_core_filesourcetask_filesprocessedcount{connectorName=~\"($connector)_file_connector\"}[1h])) by (connectorName)",
       "legendFormat": "{{connectorName}}"
      }
     ]
    },
    {
     "title": "Total Record over $interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval])) by (connectorName)",
       "legendFormat": "{{connectorName}}"
      }
     ]
    },
    {
     "title": "Total Record $interval - status OK",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
       "legendFormat": "{{connectorName}}"
      }
     ]
    },
    {
     "title": "Total Record $interval - status KO",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
       "legendFormat": "{{connectorName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stream Connector Data Feed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Record (Count / Second)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_evolving_nglm_core_streamsourcetask_totalrecordcount{connectorName=~\"$stream_connector.*\"}[1h])) by (connectorName)",
       "legendFormat": "{{ connectorName }}"
      }
     ]
    },
    {
     "title": "Total Record $interval - status OK",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount{}[$interval]) * 100 / (increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount{}[$interval]) + increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount{}[$interval]))) by (connectorName)",
       "legendFormat": "{{connectorName}}"
      }
     ]
    },
    {
     "title": "Total Record $interval - status KO",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount{}[$interval]) * 100 / (increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount{}[$interval]) + increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount{}[$interval]))) by (connectorName)",
       "legendFormat": "{{connectorName}}"
      }
     ]
    }
   ]
  },
  { "title": "License Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "License Validity (Number of Days)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(com_evolving_nglm_core_licenseexpiry_daysbeforeexpiry)"
    }
   ]
  }
 ]
}