{
 "title": "Support - Platform Health Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application_job",
    "query": {
     "query": "up{job!~\"kafkalagexporter|notificationmanager.*\"}"
    }
   },
   {
    "name": "core_job",
    "query": "up{job!~\"burrow|prometheus-core|suspenseprocesor\"}"
   },
   { "name": "node", "query": { "query": "up" } }
  ]
 },
 "panels": [
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "License Validity (Days)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "com_evolving_nglm_core_licenseexpiry_daysbeforeexpiry",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "ALERT - License Validity (Days)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum((com_evolving_nglm_core_licenseexpiry_daysbeforeexpiry)/2)by(instance, id)",
       "legendFormat": "{{instance}} {{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Machine Up / Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "repeat": "node",
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    },
    {
     "title": "$node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=~\".*$node.*9101\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Up / Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 0, "y": 10 },
     "repeat": "core_job",
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 2.6666666666666665, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 5.333333333333333, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 8, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 10.666666666666666, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 13.333333333333332, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 15.999999999999998, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 18.666666666666664, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$core_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2.6666666666666665, "x": 21.333333333333332, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$core_job\"}) / count by(job) (up{job=\"$core_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Up / Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
     "repeat": "application_job",
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "$application_job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum by(job) (up{job=\"$application_job\"}) / count by(job) (up{job=\"$application_job\"})",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "History Machines Up / Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "History Machine Up / Down",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (up) / count by (instance) (up)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "History Core Up / Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "History Core Up / Down",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(job) (up) / count by(job) (up)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  { "title": "History Application Up / Down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "History Application Up / Down",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(job) (up{job!~\"kafkalagexporter|notificationmanager.*\"}) / count by(job) (up{job!~\"kafkalagexporter|notificationmanager.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}