{
 "title": "Monitoring Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "channel_name", "query": "messagegateway" },
   {
    "name": "connector",
    "label": "CDR Source",
    "query": "com_evolving_nglm_core_filesourcetask_filesprocessedcount"
   },
   { "name": "interval", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg CPU / node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - avg by(instance) (irate(node_cpu{mode=\"idle\"}[5m]) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used memory / node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal - node_memory_MemAvailable) / node_memory_MemTotal",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk space used / instance (smallest)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max by(instance) (1 - node_filesystem_free{device!=\"rootfs\"} / node_filesystem_size{device!=\"rootfs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Data transfer / node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (rate(node_network_receive_bytes{device!~\"lo\", device!~\"docker\"}[5m]) + rate(node_network_transmit_bytes{device!~\"lo\", device!~\"docker\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "CDR Data Feed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CDR Current File Lag/Backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_total_lag{group=~\"fileconnector-($connector)_file_connector.*\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": " $connector File - current/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_filesourcetask_filesprocessedcount{connectorName=~\"($connector)_file_connector\"}[5m])) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": "Total Record $interval - status OK",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": "Total Record $interval - status KO",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  { "title": "Notifications - $channel_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_notificationstatistics_nbmessagesdelivered{}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_notificationstatistics_nbmessagefailed{}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Success rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_notificationstatistics_nbmessagesdelivered{serviceName=~\".*deliverymanager.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Failure rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_notificationstatistics_nbmessagefailed{serviceName=~\".*deliverymanager.*\"}[5m]))"
    }
   ]
  },
  { "title": "BDR-  Bonus Detail Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_bdrstatistics_nbeventsdelivered{}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_bdrstatistics_nbeventsfailed{}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Success rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_bdrstatistics_nbeventsdelivered{serviceName!~\".*deliverymanager.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Failure rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_bdrstatistics_nbeventsfailed{serviceName!~\".*deliverymanager.*\"}[5m]))"
    }
   ]
  },
  { "title": "ODR - Offer Detail Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_odrstatistics_nbpurchasesdelivered[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_odrstatistics_nbpurchasesfailed[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Success rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_odrstatistics_nbpurchasesdelivered[5m]))"
    }
   ]
  },
  {
   "title": "Failure rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_odrstatistics_nbpurchasesfailed[5m]))"
    }
   ]
  },
  { "title": "TDR - Token Detail Record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_tdrstatistics_nbpurchasesdelivered[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_tdrstatistics_nbpurchasesfailed[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Success rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_tdrstatistics_nbpurchasesdelivered[5m]))"
    }
   ]
  },
  {
   "title": "Failure rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_tdrstatistics_nbpurchasesfailed[5m]))"
    }
   ]
  },
  { "title": "3'rd Party API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_successfulapirequestcount[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Rate / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_thirdpartyaccess_successfulapirequestcount[5m]))"
    }
   ]
  },
  { "title": "GUI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  { "title": "License Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "License Validity Status - days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avg(com_evolving_nglm_core_licenseexpiry_daysbeforeexpiry)"
    }
   ]
  }
 ]
}