{
 "title": "DevOps - JVM Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GC Performance - Kafka Brokers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Young GC Time" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\", instance=~\".*7071.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*7071.*\"}[2m])) * 1000",
     "legendFormat": "{{instance}}, Young Gen"
    },
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\", instance=~\".*7071.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*7071.*\"}[2m])) * 1000",
     "legendFormat": "{{instance}}, Old Gen"
    }
   ]
  },
  {
   "title": "GC Performance - Kafka Streams",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Young GC Time" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\", instance=~\".*cluster02:9.*|.*cluster03:9.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*cluster02:9.*|.*cluster03:9.*\"}[2m])) * 1000",
     "legendFormat": "{{instance}},Old Gen"
    },
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\", instance=~\".*cluster02:9.*|.*cluster03:9.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*cluster02:9.*|.*cluster03:9.*\"}[2m])) * 1000",
     "legendFormat": "{{instance}},Young Gen"
    }
   ]
  },
  {
   "title": "Heap Size - Kafka Brokers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "Heap Size" }
   ],
   "targets": [
    {
     "expr": "sum without(area) (jvm_memory_bytes_used{instance=~\".*7071.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Size - Zookeeper",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes", "label": "Heap Size" }
   ],
   "targets": [
    {
     "expr": "sum without(area) (jvm_memory_bytes_used{instance=~\".*2301.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Performance - Zookeeper",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "Young GC Time" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\", instance=~\".*2301.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*2301.*\"}[2m])) * 1000",
     "legendFormat": "{{gc}}, Young Gen"
    },
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\", instance=~\".*2301.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*2301.*\"}[2m])) * 1000",
     "legendFormat": "{{gc}}, Old Gen"
    }
   ]
  },
  {
   "title": "GC Performance - Connect",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms", "label": "Young GC Time" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\", instance=~\".*cluster02:7.*|.*cluster03:7.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*cluster02:7.*|.*cluster03:7.*\"}[2m])) * 1000",
     "legendFormat": "{{instance}},Old Gen"
    },
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\", instance=~\".*cluster02:7.*|.*cluster03:7.*\"}[2m]) / rate(jvm_gc_collection_seconds_count{instance=~\".*cluster02:7.*|.*cluster03:7.*\"}[2m])) * 1000",
     "legendFormat": "{{instance}},Young Gen"
    }
   ]
  },
  {
   "title": "Heap Size - Kafka Streams",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes", "label": "Heap Size" }
   ],
   "targets": [
    {
     "expr": "sum without(area) (jvm_memory_bytes_used{instance=~\".*cluster02:9.*|.*cluster03:9.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Size - Connect",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "decbytes", "label": "Heap Size" }
   ],
   "targets": [
    {
     "expr": "sum without(area) (jvm_memory_bytes_used{instance=~\".*cluster02:7.*|.*cluster03:7.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}