{
 "title": "DevOps - Kafka Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Produced",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kmf_services_produce_service_records_produced_rate"
    }
   ]
  },
  {
   "title": "99.9 Delay (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_999th"
    }
   ]
  },
  {
   "title": "Max delay (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_max"
    }
   ]
  },
  {
   "title": "Min delay (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_avg"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_lost_rate"
    }
   ]
  },
  {
   "title": "Total Lag (now)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kafka_burrow_total_lag)" }
   ]
  },
  {
   "title": "Total Lag (history)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_total_lag{group!~\".*GuiManager.*\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Real time Lag (history)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_total_lag{group=\"acceptancelog\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-request-group\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-async-group\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-routing-group\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-provisioning\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"presentationlog\"}",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "kafka_burrow_total_lag{group=\"dnbo-rewardmanager-routing-group\"}",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}