{
 "title": "Support - CDR",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  { "title": "File Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CDR Current File Lag / Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_burrow_partition_lag{topic=~\".*.-fileconnector\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Record Status over the period",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_evolution_cdrline_count_total[$__range]))by(name,status)/on(name) group_left sum(increase(com_evolving_nglm_evolution_cdrline_count_total[$__range]))by(name)",
     "legendFormat": "{{name}}-{{status}}"
    },
    {
     "expr": "sum(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount[$__range]))by(connectorName)/(sum(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount[$__range]))by(connectorName) + sum(increase(com_evolving_nglm_core_filesourcetask_errorrecordcount[$__range]))by(connectorName))",
     "legendFormat": "{{connectorName}}-ok"
    },
    {
     "expr": "sum(increase(com_evolving_nglm_core_filesourcetask_errorrecordcount[$__range]))by(connectorName)/(sum(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount[$__range]))by(connectorName) + sum(increase(com_evolving_nglm_core_filesourcetask_errorrecordcount[$__range]))by(connectorName))",
     "legendFormat": "{{connectorName}}-ko"
    }
   ]
  },
  {
   "title": "File / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_filesourcetask_filesprocessedcount[$__rate_interval])) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_cdrfile_count_total[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Record / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_filesourcetaskrecord_recordcount[$__rate_interval])) by (recordType)",
     "legendFormat": "{{recordType}}"
    },
    {
     "expr": "sum(rate(com_evolving_nglm_evolution_cdrline_count_total[$__rate_interval])) by (name)",
     "legendFormat": "{{name }}"
    }
   ]
  },
  { "title": "Stream Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": " Record / Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_streamsourcetask_totalrecordcount[$__rate_interval])) by (instance, connectorName)",
     "legendFormat": "{{instance}} {{ connectorName }}"
    }
   ]
  },
  {
   "title": "Total Record over the period - status OK",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount[$__range]) * 100 / (increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount[$__range]) + increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount[$__range]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": "Total Record over the period - status KO",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount[$__range]) * 100 / (increase(com_evolving_nglm_core_streamsourcetask_totalrecordcount[$__range]) + increase(com_evolving_nglm_core_streamsourcetask_errorrecordcount[$__range]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  }
 ]
}