{
 "title": "General Dashboard - Customers and Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dimensions",
    "label": "Dimensions",
    "query": "{\"find\" : \"fields\", \"type\": \"keyword\"}"
   },
   {
    "name": "metrics",
    "label": "Metrics",
    "query": "{\"find\" : \"fields\", \"type\": \"number\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Customers by $dimensions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimensions",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Number of Customers by $dimensions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "Number of Customers" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimensions",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Average of $metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "repeat": "metrics",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimensions",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "metric.custom.$metrics",
       "hide": true,
       "id": "4",
       "inlineScript": null,
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "5",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": { "script": "(params.var2  / params.var1)" },
       "type": "bucket_script"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Sum of $metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "repeat": "metrics",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "filter.stratum.$dimensions",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metric.custom.$metrics",
       "id": "4",
       "inlineScript": null,
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}