{
 "title": "Support - CDR",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "connector",
    "label": "CDR Source",
    "query": "com_evolving_nglm_core_filesourcetask_filesprocessedcount"
   },
   { "name": "interval", "query": "1m" }
  ]
 },
 "panels": [
  { "title": "Alert", "type": "alertlist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CDR Current File Lag/Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_total_lag{group=~\"fileconnector-($connector)_file_connector.*\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Total Record $interval - status OK",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": "Total Record $interval - status KO",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "avg(increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) * 100 / (increase(com_evolving_nglm_core_filesourcetask_totalrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]) + increase(com_evolving_nglm_core_filesourcetask_errorrecordcount{connectorName=~\"($connector)_file_connector\"}[$interval]))) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": " $connector File - current/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_filesourcetask_filesprocessedcount{connectorName=~\"($connector)_file_connector\"}[5m])) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  },
  {
   "title": " $connector Record - current/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(com_evolving_nglm_core_filesourcetaskrecord_recordcount{recordType=~\"$connector.*\"}[10m])) by (recordType)",
     "legendFormat": "{{ recordType }}"
    }
   ]
  },
  {
   "title": "ALERT - Number CDR File - last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_evolving_nglm_core_filesourcetask_filesprocessedcount{connectorName=~\"($connector)_file_connector\"}[1h])) by (connectorName)",
     "legendFormat": "{{connectorName}}"
    }
   ]
  }
 ]
}