USE `dbframework`;
SET NAMES utf8 ;

DELIMITER ;;
CREATE DEFINER=`root`@`%` PROCEDURE `stp_proc_install_JMR`()
BEGIN

  IF ('true' = 'JMR_INSTALL' ) then
  
	INSERT INTO `dbframework`.`tbl_apps`(`app_key`,`app_name`,`app_description`,`app_logo`,`web_link`,`app_path`)  
	SELECT * FROM (SELECT 'JMR' as `app_key`,'JMR' as `app_name`,'Journey Manager' as `app_description`,'jmr_components/styles/images/jmr.png','JMR_URL_WEB_SERVER_PATH' as `web_link`,'/jmr' as `app_path`) AS tmp WHERE NOT EXISTS (SELECT `app_key` FROM `dbframework`.`tbl_apps` WHERE `app_key` = 'JMR') LIMIT 1;
	SELECT `app_id` INTO @app_id FROM `dbframework`.`tbl_apps` WHERE `app_key` = 'JMR';
	SELECT `workgroup_id` INTO @wid from `dbframework`.`tbl_workgroups` WHERE `workgroup_key`='WKG-ADMIN';
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-ACCESS' as  `permission_key` ,'Access' as `permission_name`,'Journey Manager' as `permission_description` ,@app_id as `app_id`,null as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-ACCESS') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-ACCESS';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-JOURNEYS' as  `permission_key` ,'Journeys' as `permission_name`,'Access Journeys module' as `permission_description` ,@app_id as `app_id`,'Journeys' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-JOURNEYS') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-JOURNEYS';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-JOURNEYS-ADD-EDIT' as  `permission_key` ,'Add/Edit' as `permission_name`,'Add/Edit Journey' as `permission_description` ,@app_id as `app_id`,'Journeys' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-JOURNEYS-ADD-EDIT') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-JOURNEYS-ADD-EDIT';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-JOURNEYS-DELETE' as  `permission_key` ,'Delete' as `permission_name`,'Delete Journey' as `permission_description` ,@app_id as `app_id`,'Journeys' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-JOURNEYS-DELETE') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-JOURNEYS-DELETE';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-CAMPAIGNS' as  `permission_key` ,'Campaigns' as `permission_name`,'Access Campaigns module' as `permission_description` ,@app_id as `app_id`,'Campaigns' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-CAMPAIGNS') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-CAMPAIGNS';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-CAMPAIGNS-ADD-EDIT' as  `permission_key` ,'Add/Edit' as `permission_name`,'Add/Edit Campaign' as `permission_description` ,@app_id as `app_id`,'Campaigns' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-CAMPAIGNS-ADD-EDIT') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-CAMPAIGNS-ADD-EDIT';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-CAMPAIGNS-DELETE' as  `permission_key` ,'Delete' as `permission_name`,'Delete Campaign' as `permission_description` ,@app_id as `app_id`,'Campaigns' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-CAMPAIGNS-DELETE') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-CAMPAIGNS-DELETE';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-PROGRAMS' as  `permission_key` ,'Programs' as `permission_name`,'Access Programs module' as `permission_description` ,@app_id as `app_id`,'Programs' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-PROGRAMS') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-PROGRAMS';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-PROGRAMS-ADD-EDIT' as  `permission_key` ,'Add/Edit' as `permission_name`,'Add/Edit Program' as `permission_description` ,@app_id as `app_id`,'Programs' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-PROGRAMS-ADD-EDIT') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-PROGRAMS-ADD-EDIT';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-PROGRAMS-DELETE' as  `permission_key` ,'Delete' as `permission_name`,'Delete Program' as `permission_description` ,@app_id as `app_id`,'Programs' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-PROGRAMS-DELETE') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-PROGRAMS-DELETE';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-JOURNEYS-START' as  `permission_key` ,'Start' as `permission_name`,'Permission to start a journey' as `permission_description` ,@app_id as `app_id`,'Journeys' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-JOURNEYS-START') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-JOURNEYS-START';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-JOURNEYS-STOP' as  `permission_key` ,'Stop' as `permission_name`,'Permission to stop journey' as `permission_description` ,@app_id as `app_id`,'Journeys' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-JOURNEYS-STOP') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-JOURNEYS-STOP';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-CAMPAIGNS-START' as  `permission_key` ,'Start' as `permission_name`,'Permission to start a campaign' as `permission_description` ,@app_id as `app_id`,'Campaigns' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-CAMPAIGNS-START') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-CAMPAIGNS-START';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	INSERT INTO `dbframework`.`tbl_permissions`(`permission_key`,`permission_name`,`permission_description`,`app_id`,`folder`) SELECT * FROM (SELECT 'JMR-CAMPAIGNS-STOP' as  `permission_key` ,'Stop' as `permission_name`,'Permission to stop a campaign' as `permission_description` ,@app_id as `app_id`,'Campaigns' as `folder`) AS tmp WHERE NOT EXISTS (SELECT `permission_key` FROM `dbframework`.`tbl_permissions` WHERE `permission_key` = 'JMR-CAMPAIGNS-STOP') LIMIT 1;
	SELECT permission_id INTO @perid from  `dbframework`.`tbl_permissions` WHERE `permission_key`='JMR-CAMPAIGNS-STOP';
	INSERT INTO `dbframework`.`tbl_workgroups_permissions`(`workgroup_id`,`permission_id`) SELECT * FROM (SELECT @wid as `workgroup_id` ,@perid as `permission_id`) AS tmp WHERE NOT EXISTS ( SELECT `workgroup_id` FROM `dbframework`.`tbl_workgroups_permissions` WHERE `workgroup_id` = @wid AND `permission_id`=@perid) LIMIT 1;
	  
  END IF;
END ;;
DELIMITER ;

-- Execute the procedure
call `dbframework`.`stp_proc_install_JMR`();

-- Drop the procedure
DROP PROCEDURE `dbframework`.`stp_proc_install_JMR`;